### ISSUE TITLE
Select Ride issue

### ISSUE THREAD

**Issue by Jordanjtt97** [autosysops/OpenRct2RideEditor#1]
When I go to pick the ride I want to edit, it shows me up to 150 options but it includes everything from rides to stalls which I don’t understand why stalls are there anyways since they aren’t rides.  But point being I can’t see all the rides or the specific one I’d like to edit.
![image](https://user-images.githubusercontent.com/113310493/189546320-4a0c09a9-7048-49ef-b040-6573ef7573cc.jpg)

**Comment by autosysops** [comment]
Will look into this, thanks for pointing it out.

**Comment by autosysops** [comment]
My proposed solution would be to create a seperate window where you can select the ride which shows all the rides but with filters available. Would that work for you? I think there are reasons why you do wnat to see the shops in there but being able to filter and remove shops for example could help you find. Maybe I could even add a search bar in the window.

**Comment by autosysops** [comment]
@Jordanjtt97 the new version should solve this problem. Sorry it took so long.
