### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by astraylife1** [autosysops/OpenRct2RideEditor#3]
This is one of my favorite plugins. I was wondering if it could be made possible so that the ride list is alphabetical rather than by ride ID. 

Also, if the plugin would remember which ride you had last selected so that when you reopen the plugin, it will already be set to that ride.

**Comment by autosysops** [comment]
My proposed solution would be to create a seperate window where you can select the ride which shows all the rides but with filters available. Would that work for you? I think there are reasons why you do wnat to see the shops in there but being able to filter and remove shops for example could help you find. Maybe I could even add a search bar in the window.
It would also have a sorting option.

**Comment by astraylife1** [comment]
That could work. Or even just a checkbox “hide stalls from list” or something. The most important features I’d like are the alphabetical list and if it could remember which ride I was just using if I am opening and closing it multiple times within the same park. 
Really appreciate you looking into all this. This plugin is one of my faves and I always promote it on mg YouTube OpenRCT2Tutorials.

**Comment by autosysops** [comment]
@astraylife1 could you test this version for me?
https://github.com/autosysops/OpenRct2RideEditor/blob/dev/RideEditor.js
(you can press the raw button to get the full file, copy it into the rideeditor.js file in the plugin folder).
This should remember which ride you where editing per savegame. Only if you save the game will it remember it (the last edited ride is stored in the savegame data)

**Comment by astraylife1** [comment]
I'll give it a go, thanks

**Comment by autosysops** [comment]
@astraylife1 thanks, let me know if it works for you then I can release this version at least

**Comment by astraylife1** [comment]
I’ve played a with it and it works. Haven’t noticed any bugs. No chance on an alphabetized list?

**Comment by autosysops** [comment]
> I’ve played a with it and it works. Haven’t noticed any bugs. No chance on an alphabetized list?

next update. that takes a bit more work

**Comment by astraylife1** [comment]
Sounds great! Really appreciate all this. One of my fave plugins

**Comment by autosysops** [comment]
@astraylife1 the new version now supports the alphabetized list too.
